tab_spaces = 4
trailing_comma = "Always"
trailing_semicolon = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
use_try_shorthand = true
fn_params_layout = "Tall"
remove_nested_parens = true
format_code_in_doc_comments = true
comment_width = 100
wrap_comments = true
