[package]
name = "svm-alm-controller-client"
description = "Generated client for myproject"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "svm_alm_controller_client"
path = "src/lib.rs"

[features]
serde = []
fetch = []
anchor = []
anchor-idl-build = []

[dependencies]
borsh = { workspace = true }
solana-program = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true}
solana-sdk = { workspace = true }
spl-associated-token-account-client = { workspace = true }
spl-token = { workspace = true }