name: Build Verifiable SVM ALM Controller
# Creates a verifiable build artifact

on:
  push:
    tags:
      - "build-v*"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  security_audit:
    name: security_audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-audit from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-audit
      - run: cargo audit --ignore RUSTSEC-2022-0093 --ignore RUSTSEC-2023-0065 --ignore RUSTSEC-2024-0344 --ignore RUSTSEC-2024-0421

  verified_build:
    name: verified_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install solana-verify dependencies
        run: sudo apt-get install libudev-dev
      - name: Pull solana-verifiable-build Docker image
        run: docker pull --platform linux/amd64 solanafoundation/solana-verifiable-build:2.2.20
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install solana-verify from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: solana-verify
      - name: Build svm-alm-controller with verifiable build
        run: solana-verify build --library-name svm-alm-controller --base-image solanafoundation/solana-verifiable-build:2.2.20
        # step successfully builds, but errors parsing output.
        # We should continue to attempt to upload the artifact.
        continue-on-error: true
      - name: Upload svm-alm-controller
        uses: actions/upload-artifact@v4
        with:
          name: svm_alm_controller.so
          path: ./target/deploy/svm_alm_controller.so

  test_build:
    name: Test verifiable build
    runs-on: ubuntu-latest
    needs:
      - verified_build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: svm_alm_controller.so
          path: ./target/deploy
      - name: Download OpenSSL
        run: sudo apt-get install -y libssl-dev
      - name: Test verifiable build
        run: cargo test
